name: 🐛 Bug Report
description: 回報錯誤問題
title: "[BUG] <問題描述>"
labels: ["bug", "MissionType:Bug"]
body:
  - type: textarea
    id: what_happened
    attributes:
      label: 💥 問題描述
      description: 發生了什麼問題？重現步驟是什麼？
      placeholder: |
        - 啟動系統
        - 點選登入按鈕
        - 無反應
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ 預期行為
      placeholder: 預期登入後應跳轉至 Dashboard
    validations:
      required: false

  - type: input
    id: env
    attributes:
      label: 🧪 測試環境（可選）
      placeholder: e.g., Chrome 118, Ubuntu 22.04
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 📋 錯誤日誌 / 截圖（可選）
      placeholder: 請附上錯誤訊息或截圖
    validations:
      required: false

  - type: input
    id: priority
    attributes:
      label: 🚨 優先級（High / Medium / Low）
      placeholder: High
    validations:
      required: false
