name: 🐞 Bug Report
description: 回報系統錯誤或異常行為
title: "[BUG] <請輸入錯誤簡述>"
labels: ["bug", "MissionType:Bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: ❗ 問題描述
      placeholder: 請簡單說明發生了什麼問題
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🧪 重現步驟
      placeholder: |
        請具體說明如何重現這個 bug，例如：
        1. 登入帳號
        2. 點選「提交」
        3. 出現錯誤訊息
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ 預期行為
      placeholder: 原本應該要發生什麼？
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: 🖼️ 錯誤畫面（建議上傳圖片）
      description: 可將圖片拖曳進來，或複製貼上
      placeholder: 請將截圖拖進來或 Ctrl+V 貼上
    validations:
      required: false

  - type: textarea
    id: env
    attributes:
      label: 🧰 執行環境
      placeholder: |
        - 裝置 / 瀏覽器：Windows / Chrome 116
        - 登入帳號狀態：已登入
        - 網路環境：公司內部 / VPN
    validations:
      required: false
