name: 🚀 Feature Request / Subtask
description: 提交新功能或子任務
title: "[FEATURE] <功能名稱>"
labels: ["feature", "MissionType:Feature"]
body:
  - type: dropdown
    id: is_subtask
    attributes:
      label: 📂 是否為子任務（Subtask）
      options:
        - 否，這是獨立功能（Epic）
        - 是，這是 Epic 之下的一個子任務
      default: 1
    validations:
      required: true

  - type: input
    id: parent_issue
    attributes:
      label: 🔗 若為子任務，請填 Epic Issue ID（如 #123）
      placeholder: "#123"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: ✨ 功能描述
      placeholder: 功能要做什麼？誰會使用？預期怎樣？
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: 👤 使用者故事（可選）
      placeholder: |
        範例：
        - 作為訪客，我希望可以快速註冊，這樣我就能建立個人帳號。
    validations:
      required: false

  - type: input
    id: priority
    attributes:
      label: ⏱️ 優先級（High / Medium / Low）
      placeholder: Medium
    validations:
      required: false

  - type: dropdown
    id: is_security
    attributes:
      label: 🔒 是否為資安相關項目？
      options:
        - 否
        - 是（Chore）
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 📎 備註（可選）
    validations:
      required: false
